---
title: "Step 3: create_export_check"
author: "Caylyn and Rose"
date: "7/21/2021"
output: html_document
---

```{r}
library(dplyr)
library(tidyr)
```

#THERE ARE A COUPLE WAYS TO DO THIS

```{r}
#List of files used 
sample.list <- read.table("~/Desktop/Lab_Work/linc_RNA/phenotyping/Script/rose_script/R2_Clean.txt", 
                          sep ="\t", header = F)
sample.list


#Export files (OPTIONAL)
raspiS_cameraA.transform <- read.csv(paste0("~/Desktop/Lab_Work/linc_RNA/phenotyping/Round2/Round2_clean_csv_files/r_script_practice/",sample.list[1,1],".csv"), header = T)
raspiS_cameraB.transform <- read.csv(paste0("~/Desktop/Lab_Work/linc_RNA/phenotyping/Round2/Round2_clean_csv_files/r_script_practice/",sample.list[2,1],".csv"), header = T)
raspiU_cameraA.transform <- read.csv(paste0("~/Desktop/Lab_Work/linc_RNA/phenotyping/Round2/Round2_clean_csv_files/r_script_practice/",sample.list[3,1],".csv"), header = T)
raspiU_cameraB.transform <- read.csv(paste0("~/Desktop/Lab_Work/linc_RNA/phenotyping/Round2/Round2_clean_csv_files/r_script_practice/",sample.list[4,1],".csv"), header = T)
raspiT_cameraA.transform <- read.csv(paste0("~/Desktop/Lab_Work/linc_RNA/phenotyping/Round2/Round2_clean_csv_files/r_script_practice/",sample.list[5,1],".csv"), header = T)
raspiT_cameraB.transform <- read.csv(paste0("~/Desktop/Lab_Work/linc_RNA/phenotyping/Round2/Round2_clean_csv_files/r_script_practice/",sample.list[6,1],".csv"), header = T)
```


```{r}
#Change data types of columns to make sure all column data types match
raspiU_cameraA.transform$in_bounds <- as.character(raspiU_cameraA.transform$in_bounds)
raspiU_cameraA.transform$object_in_frame <- as.character(raspiU_cameraA.transform$object_in_frame)  

#Create Meta phenotype sheet by combining multiple files
merge_list <- lapply(ls(pattern = "raspi"), get)
```

ORRR do this 

```{r}
raspiK_cameraA_clean <- read.csv ("/Users/caylynrailey/Desktop/Lab_Work/lncRNA/lincRNA_phenotyping/Round3/clean_csv/raspiK_cameraA_rclean.csv")
raspiK_cameraB_clean <- read.csv ("/Users/caylynrailey/Desktop/Lab_Work/lncRNA/lincRNA_phenotyping/Round3/clean_csv/raspiK_cameraB_rclean.csv")

raspiM_cameraA_clean <- read.csv ("/Users/caylynrailey/Desktop/Lab_Work/lncRNA/lincRNA_phenotyping/Round3/clean_csv/raspiM_cameraA_rclean.csv")
raspiM_cameraB_clean <- read.csv ("/Users/caylynrailey/Desktop/Lab_Work/lncRNA/lincRNA_phenotyping/Round3/clean_csv/raspiM_cameraB_rclean.csv")

raspiU_cameraA_clean <- read.csv ("/Users/caylynrailey/Desktop/Lab_Work/lncRNA/lincRNA_phenotyping/Round3/clean_csv/raspiU_cameraA_rclean.csv")
raspiU_cameraB_clean <- read.csv ("/Users/caylynrailey/Desktop/Lab_Work/lncRNA/lincRNA_phenotyping/Round3/clean_csv/raspiU_cameraB_rclean.csv")

```


```{r}
raspiK_cameraA_clean$in_bounds <- as.character(raspiK_cameraA_clean$in_bounds)
raspiK_cameraA_clean$object_in_frame <- as.character(raspiK_cameraA_clean$object_in_frame)  

raspiM_cameraA_clean$in_bounds <- as.character(raspiM_cameraA_clean$in_bounds)
raspiM_cameraA_clean$object_in_frame <- as.character(raspiM_cameraA_clean$object_in_frame)  

raspiU_cameraA_clean$in_bounds <- as.character(raspiU_cameraA_clean$in_bounds)
raspiU_cameraA_clean$object_in_frame <- as.character(raspiU_cameraA_clean$object_in_frame)  


raspiK_cameraB_clean$in_bounds <- as.character(raspiK_cameraB_clean$in_bounds)
raspiK_cameraB_clean$object_in_frame <- as.character(raspiK_cameraB_clean$object_in_frame)  

raspiM_cameraB_clean$in_bounds <- as.character(raspiM_cameraB_clean$in_bounds)
raspiM_cameraB_clean$object_in_frame <- as.character(raspiM_cameraB_clean$object_in_frame)  

raspiU_cameraB_clean$in_bounds <- as.character(raspiU_cameraB_clean$in_bounds)
raspiU_cameraB_clean$object_in_frame <- as.character(raspiU_cameraB_clean$object_in_frame)  


```


```{r}
raspi_combined_r3 <- bind_rows(raspiK_cameraA_clean, raspiK_cameraB_clean, raspiM_cameraA_clean, raspiM_cameraB_clean, raspiU_cameraA_clean, raspiU_cameraB_clean)



raspi_clean_r3 <- raspi_combined_r3[,c(3,16,17,18,19,20,21,22,23,24,25,26,27,28)]
write.csv(raspi_clean_r3, "~/Desktop/export_check_r3.csv", row.names = F)

```
```

